.PHONY: all

all: import-html-bootcamp.log # import-html-pdf-cn-rs.log

import-html-bootcamp.log: ${@:.log:.sh}
	bash import-html-bootcamp.sh

# import-html-pdf-cn-rs.log: ${@:.log:.sh}
#	bash import-html-pdf-cn-rs.sh
